# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Mar  3 18:05:38 2020
# ------------------------------------------------

package:
    name: zipp
    version: 3.1.0
source:
    patches:
        - use-scm-version.patch
    sha256: c599e4d75c98f6798c509911d08a22e6c021d074469042177c8c86fb92eefd96
    url: https://pypi.io/packages/source/z/zipp/zipp-3.1.0.tar.gz
build:
    noarch: python
    number: '0'
    script: '/home/conda/feedstock_root/build_artifacts/zipp_1583258794306/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . --no-deps --ignore-installed -vv '
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2019.11.28 hecc5488_0
        - certifi 2019.11.28 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_8
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d h516909a_0
        - pip 20.0.2 py_2
        - python 3.8.2 h9d8adfe_1_cpython
        - readline 8.0 hf8c457e_0
        - setuptools 45.2.0 py38_0
        - setuptools_scm 3.5.0 py_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - toml 0.10.0 py_0
        - wheel 0.34.2 py_1
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
    run:
        - python >=3.6
test:
    commands:
        - python -m unittest test_zipp.py
        - pip check
    imports:
        - zipp
    requires:
        - func_timeout
        - importlib_metadata
        - jaraco.itertools
        - pip
    source_files:
        - test_zipp.py
about:
    dev_url: https://github.com/jaraco/zipp
    doc_url: https://zipp.readthedocs.io/en/latest
    home: https://github.com/jaraco/zipp
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: A pathlib-compatible Zipfile object wrapper
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
