# This file created by conda-build 3.19.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Mar 29 14:02:35 2020
# ------------------------------------------------

package:
    name: importlib-metadata
    version: 1.6.0
source:
    sha256: 34513a8a0c4962bc66d35b359558fd8a5e10cd472d37aec5f66858addef32c1e
    url: https://pypi.io/packages/source/i/importlib_metadata/importlib_metadata-1.6.0.tar.gz
build:
    number: '0'
    string: py37hc8dfbb8_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2019.11.28 hecc5488_0
        - certifi 2019.11.28 py37hc8dfbb8_1
        - ld_impl_linux-64 2.34 h53a641e_0
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1e h516909a_0
        - pip 20.0.2 py_2
        - python 3.7.6 h8356626_5_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 hf8c457e_0
        - setuptools 46.1.3 py37hc8dfbb8_0
        - setuptools-scm 3.5.0 py_1
        - setuptools_scm 3.5.0 1
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py_1
        - xz 5.2.4 h516909a_1002
        - zlib 1.2.11 h516909a_1006
    run:
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - zipp >=0.5
about:
    home: https://gitlab.com/python-devs/importlib_metadata
    license: Apache-2.0
    license_family: APACHE
    license_file: LICENSE
    summary: A library to access the metadata for a Python package
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
        - nicoddemus
