# This file created by conda-build 3.16.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/nodejs-10.13.0-on-linux_64, last modified Fri Nov  2 16:25:33 2018
# ------------------------------------------------

package:
    name: nodejs
    version: 10.13.0
source:
    fn: node-v10.13.0.tar.gz
    patches:
        - 0001-macOS-use-MACOSX_DEPLOYMENT_TARGET-10.9.patch
    sha256: aa06825fff375ece7c0d881ae0de5d402a857e8cabff9b4a50f2f0b7b44906be
    url: https://nodejs.org/dist/v10.13.0/node-v10.13.0.tar.gz
build:
    ignore_prefix_files:
        - bin/node
    missing_dso_whitelist:
        - /usr/lib/libSystem.B.dylib
    number: '0'
    string: he6710b0_0
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - ca-certificates 2018.03.07 0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_3
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - make 4.2.1 h1bed415_1
        - ncurses 6.1 hf484d3e_0
        - openssl 1.1.1 h7b6447c_0
        - python 2.7.15 h9bab390_2
        - readline 7.0 h7b6447c_5
        - sqlite 3.25.2 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - zlib 1.2.11 ha838bed_2
    host:
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
test:
    commands:
        - node -h
        - node -v
        - npm version
        - npm install -h
        - npm config get prefix -g
        - test $(echo "console.log(1 + 3)" | node) == 4
about:
    home: https://nodejs.org/
    license: MIT
    license_file: LICENSE
    summary: a platform for easily building fast, scalable network applications
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
        - msarahan
        - pelson
