# This file created by conda-build 3.18.12
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Mar  4 14:37:53 2020
# ------------------------------------------------

package:
    name: pycparser
    version: '2.20'
source:
    fn: pycparser-2.20.tar.gz
    sha256: 2d475327684562c3a96cc71adf7dc8c4f0565175cf86b6d7a404ff4c771f15f0
    url: https://pypi.io/packages/source/p/pycparser/pycparser-2.20.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/pycparser_1583332729764/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
        -m pip install . -vvv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2019.11.28 hecc5488_0
        - certifi 2019.11.28 py27_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d h516909a_0
        - pip 20.0.2 py_2
        - python 2.7.15 h5a48372_1009
        - readline 8.0 hf8c457e_0
        - setuptools 44.0.0 py27_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py_1
        - zlib 1.2.11 h516909a_1006
    run:
        - python
test:
    imports:
        - pycparser
        - pycparser.ply
about:
    description: 'pycparser is a complete parser of the C language, written in pure
        Python using the PLY parsing library.

        It parses C code into an AST and can serve as a front-end for C compilers
        or analysis tools.

        '
    dev_url: https://github.com/eliben/pycparser
    home: https://github.com/eliben/pycparser
    license: BSD 3-clause
    license_file: LICENSE
    summary: Complete C99 parser in pure Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - synapticarbors
