# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Oct 15 12:38:58 2019
# ------------------------------------------------

package:
    name: attrs
    version: 19.3.0
source:
    fn: attrs-19.3.0.tar.gz
    sha256: f7b7ce16570fe9965acd6d30101a28f62fb4a7f9e926b3bbc9b61f8b04247e72
    url: https://pypi.io/packages/source/a/attrs/attrs-19.3.0.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install . --no-deps --ignore-installed
    string: py_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.9.11 hecc5488_0
        - certifi 2019.9.11 py27_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - pip 19.2.3 py27_0
        - python 2.7.15 h5a48372_1009
        - readline 8.0 hf8c457e_0
        - setuptools 41.4.0 py27_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.9 hed695b0_1003
        - wheel 0.33.6 py27_0
        - zlib 1.2.11 h516909a_1006
    run:
        - python
test:
    imports:
        - attr
    requires:
        - coverage
        - hypothesis
        - pympler
        - six
        - zope
        - zope.interface
about:
    description: 'attrs is the Python package that will bring back the joy of writing

        classes by relieving you from the drudgery of implementing object

        protocols (aka dunder methods). Its main goal is to help you to write

        concise and correct software without slowing down your code. For that, it

        gives you a class decorator and a way to declaratively define the

        attributes on that class:

        '
    dev_url: https://github.com/python-attrs/attrs
    doc_url: https://attrs.readthedocs.io/en/stable/
    home: https://attrs.readthedocs.io/en/stable/
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: attrs is the Python package that will bring back the joy of writing classes
        by relieving you from the drudgery of implementing object protocols (aka dunder
        methods).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - CJ-Wright
        - jochym
        - licode
        - nicoddemus
