# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/jupyter_client-6.1.3-on-linux_canary, last modified Fri May  1 14:46:04 2020
# ------------------------------------------------

package:
    name: jupyter_client
    version: 6.1.3
source:
    sha256: 3a32fa4d0b16d1c626b30c3002a62dfd86d6863ed39eaba3f537fade197bb756
    url: https://pypi.io/packages/source/j/jupyter_client/jupyter_client-6.1.3.tar.gz
build:
    entry_points:
        - jupyter-kernel = jupyter_client.kernelapp:main
        - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
        - jupyter-run = jupyter_client.runapp:main
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/jupyter_client_1588344488031/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py38_1
        - python 3.8.2 hcf32534_0
        - readline 8.0 h7b6447c_0
        - setuptools 46.1.3 py38_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - entrypoints
        - jupyter_core >=4.6.0
        - python >=3.5
        - python-dateutil >=2.1
        - pyzmq >=13
        - tornado >=4.1
        - traitlets
test:
    commands:
        - pip check
        - jupyter kernelspec list
        - jupyter run -h
        - pytest --pyargs jupyter_client
    imports:
        - jupyter_client
    requires:
        - ipykernel
        - ipython
        - pip
        - pytest
about:
    dev_url: https://github.com/jupyter/jupyter_client
    doc_source_url: https://github.com/jupyter/jupyter_client/tree/master/docs
    doc_url: https://jupyter-client.readthedocs.io/en/stable/
    home: https://jupyter.org
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING.md
    summary: jupyter_client contains the reference implementation of the Jupyter protocol.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - bollwyvl
        - carreau
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
