# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Feb 12 11:35:59 2020
# ------------------------------------------------

package:
    name: jupyter_telemetry
    version: 0.0.5
source:
    sha256: d3eaac14be17510a4d288f3737580107ce14eef543e6133d56654d3f0e742b9b
    url: https://pypi.io/packages/source/j/jupyter_telemetry/jupyter_telemetry-0.0.5.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/jupyter_telemetry_1581507410591/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2019.11.28 hecc5488_0
        - certifi 2019.11.28 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_8
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d h516909a_0
        - pip 20.0.2 py_2
        - python 3.8.1 h357f687_2
        - readline 8.0 hf8c457e_0
        - setuptools 45.2.0 py38_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py_1
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
    run:
        - jsonschema
        - python >=3.5
        - python-json-logger
        - ruamel.yaml
        - traitlets
test:
    imports:
        - jupyter_telemetry
about:
    description: "Telemetry provides a configurable traitlets object, EventLog,\n\
        for structured event-logging in Python.\nIt leverages Python\u2019s standard\
        \ logging library for filtering, handling, and recording events.\nAll events\
        \ are validated (using jsonschema) against registered JSON schemas.\n"
    dev_url: https://github.com/jupyter/telemetry
    doc_url: https://jupyter-telemetry.readthedocs.io
    home: https://jupyter-telemetry.readthedocs.io
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Telemetry for Jupyter Applications and extensions.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
