# This file created by conda-build 3.18.11
# ------------------------------------------------

package:
    name: jupyterhub-base
    version: 1.1.0
source:
    fn: jupyterhub-1.1.0.tar.gz
    sha256: 852a70225a03abd631b36a207f3ffdf69326a0db4cef539825fde39ec1b713d7
    url: https://pypi.io/packages/source/j/jupyterhub/jupyterhub-1.1.0.tar.gz
build:
    number: 2
    script: python -m pip install . --no-deps -vv
    string: py37_2
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2019.11.28 hecc5488_0
        - certifi 2019.11.28 py37_0
        - ld_impl_linux-64 2.33.1 h53a641e_8
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d h516909a_0
        - pip 20.0.2 py37_0
        - python 3.7.6 h357f687_2
        - readline 8.0 hf8c457e_0
        - setuptools 45.1.0 py37_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.1 py37_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
    run:
        - alembic
        - async_generator >=1.8
        - certipy >=0.1.2
        - entrypoints
        - jinja2
        - jupyter_telemetry
        - oauthlib >=3.0
        - pamela
        - prometheus_client >=0.0.21
        - pycurl
        - python >=3.7,<3.8.0a0
        - python-dateutil
        - requests
        - sqlalchemy >=1.1
        - tornado >=5.0
        - traitlets >=4.3.2
test:
    commands:
        - python -m jupyterhub --help-all
    imports:
        - jupyterhub
        - jupyterhub.apihandlers
        - jupyterhub.app
        - jupyterhub.handlers
        - jupyterhub.tests
about:
    home: https://github.com/jupyterhub/jupyterhub
    license: BSD 3-Clause
    license_file: COPYING.md
    summary: Multi-user server for Jupyter notebooks
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
