# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jan 30 05:27:24 2020
# ------------------------------------------------

package:
    name: pycurl
    version: 7.43.0.5
source:
    sha256: ec7dd291545842295b7b56c12c90ffad2976cc7070c98d7b1517b7b6cd5994b3
    url: https://pypi.io/packages/source/p/pycurl/pycurl-7.43.0.5.tar.gz
build:
    detect_binary_files_with_prefix: false
    number: '0'
    string: py37h16ce93b_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - binutils_impl_linux-64 2.33.1 h53a641e_8
        - binutils_linux-64 2.33.1 h9595d00_16
        - gcc_impl_linux-64 7.3.0 hd420e75_4
        - gcc_linux-64 7.3.0 h553295d_16
        - ld_impl_linux-64 2.33.1 h53a641e_8
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2019.11.28 hecc5488_0
        - krb5 1.16.4 h2fd8d38_0
        - ld_impl_linux-64 2.33.1 h53a641e_8
        - libcurl 7.64.1 hda55be3_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1a h14c3975_1001
        - python 3.7.6 h357f687_2
        - readline 8.0 hf8c457e_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
    run:
        - libcurl >=7.64.1,<8.0a0
        - libgcc-ng >=7.3.0
        - openssl >=1.1.1a,<1.1.2a
        - python >=3.7,<3.8.0a0
test:
    imports:
        - curl
        - pycurl
about:
    description: 'PycURL is a Python interface to libcurl, the multiprotocol file
        transfer library.

        Similarly to the urllib Python module, PycURL can be used to fetch objects
        identified

        by a URL from a Python program.

        '
    dev_url: https://github.com/pycurl/pycurl
    doc_source_url: https://github.com/pycurl/pycurl/blob/master/doc/index.rst
    doc_url: http://pycurl.io/docs/latest/index.html
    home: http://pycurl.sourceforge.net/
    license: LGPL, MIT
    license_family: LGPL
    license_file: COPYING-LGPL
    summary: A Python Interface To The cURL library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chrisburr
