# This file created by conda-build 3.19.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Mar 24 22:09:48 2020
# ------------------------------------------------

package:
    name: pyrsistent
    version: 0.16.0
source:
    sha256: 28669905fe725965daa16184933676547c5bb40a5153055a8dee2a4bd7933ad3
    url: https://pypi.io/packages/source/p/pyrsistent/pyrsistent-0.16.0.tar.gz
build:
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/pyrsistent_1585087836795/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . --no-deps --ignore-installed -vvv
    string: py37h8f50634_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - binutils_impl_linux-64 2.34 h53a641e_0
        - binutils_linux-64 2.34 hc952b39_18
        - gcc_impl_linux-64 7.3.0 hd420e75_5
        - gcc_linux-64 7.3.0 h553295d_18
        - ld_impl_linux-64 2.34 h53a641e_0
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - attrs 19.3.0 py_0
        - ca-certificates 2019.11.28 hecc5488_0
        - certifi 2019.11.28 py37hc8dfbb8_1
        - importlib-metadata 1.5.0 py37hc8dfbb8_1
        - importlib_metadata 1.5.0 1
        - ld_impl_linux-64 2.34 h53a641e_0
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - more-itertools 8.2.0 py_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1e h516909a_0
        - packaging 20.1 py_0
        - pip 20.0.2 py_2
        - pluggy 0.13.0 py37_0
        - py 1.8.1 py_0
        - pyparsing 2.4.6 py_0
        - pytest 5.4.1 py37hc8dfbb8_0
        - pytest-runner 5.2 py_0
        - python 3.7.6 h8356626_5_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 hf8c457e_0
        - setuptools 46.1.1 py37hc8dfbb8_0
        - six 1.14.0 py_1
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wcwidth 0.1.8 py_0
        - wheel 0.34.2 py_1
        - xz 5.2.4 h516909a_1002
        - zipp 3.1.0 py_0
        - zlib 1.2.11 h516909a_1006
    run:
        - libgcc-ng >=7.3.0
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - six
test:
    imports:
        - pyrsistent
    requires:
        - hypothesis
        - pytest
about:
    home: http://github.com/tobgu/pyrsistent/
    license: MIT
    license_family: MIT
    license_file: LICENCE.mit
    summary: Persistent/Functional/Immutable data structures
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
