# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed May  8 09:45:13 2019
# ------------------------------------------------

package:
    name: certipy
    version: 0.1.3
source:
    sha256: 695704b7716b033375c9a1324d0d30f27110a28895c40151a90ec07ff1032859
    url: https://pypi.io/packages/source/c/certipy/certipy-0.1.3.tar.gz
build:
    entry_points:
        - certipy = certipy.command_line:main
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/certipy_1557308855984/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2019.3.9 hecc5488_0
        - certifi 2019.3.9 py37_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - pip 19.1 py37_0
        - python 3.7.3 h5b0a415_0
        - readline 7.0 hf8c457e_1001
        - setuptools 41.0.1 py37_0
        - sqlite 3.26.0 h67949de_1001
        - tk 8.6.9 h84994c4_1001
        - wheel 0.33.1 py37_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    run:
        - pyopenssl
        - python >=3.3
test:
    commands:
        - certipy test
    imports:
        - certipy
about:
    description: 'A simple python tool for creating certificate authorities

        and certificates on the fly.

        '
    dev_url: https://github.com/LLNL/certipy
    home: https://github.com/LLNL/certipy
    license: BSD-3-Clause
    license_family: BSD
    license_file: /home/conda/recipe_root/LICENSE
    summary: Simple, fast, extensible JSON encoder/decoder for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
