# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/zeromq-4.3.1-on-linux_canary, last modified Fri Feb  1 11:32:34 2019
# ------------------------------------------------

package:
    name: zeromq
    version: 4.3.1
source:
    patches:
        - 0001-Files-required-to-include-ClangFormat-are-missing.patch
        - 0002-Install-ZeroMQConfig.cmake-on-Windows-to-same-place-.patch
        - 0003-SLES11-Hackily-avoid-pthread_set_name_np-on-linux.patch
        - 0005-osx-test.patch
    sha256: bcbabe1e2c7d0eec4ed612e10b94b112dd5f06fcefa994a0c79a45d835cd21eb
    url: https://github.com/zeromq/libzmq/releases/download/v4.3.1/zeromq-4.3.1.tar.gz
build:
    number: '3'
    run_exports:
        - zeromq >=4.3.1,<4.4.0a0
    string: he6710b0_3
requirements:
    build:
        - autoconf 2.69 pl526hebd4dad_5
        - automake 1.16.1 pl526_0
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_6
        - ca-certificates 2018.12.5 0
        - expat 2.2.6 he6710b0_0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_6
        - git 2.20.1 pl526hacde149_0
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_6
        - krb5 1.16.1 h173b8e3_7
        - libcurl 7.63.0 h20c2e04_1000
        - libedit 3.1.20181209 hc058e9b_0
        - libgcc-ng 8.2.0 hdf63c60_1
        - libssh2 1.8.0 h1ba5d50_4
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - libtool 2.4.6 h7b6447c_5
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1a h7b6447c_0
        - perl 5.26.2 h14c3975_0
        - pkg-config 0.29.2 h1bed415_8
        - tk 8.6.8 hbc83047_0
        - zlib 1.2.11 h7b6447c_3
    host:
        - libgcc-ng 8.2.0 hdf63c60_1
        - libsodium 1.0.16 h1bed415_0
        - libstdcxx-ng 8.2.0 hdf63c60_1
    run:
        - libgcc-ng >=7.3.0
        - libsodium >=1.0.16,<1.0.17.0a0
        - libstdcxx-ng >=7.3.0
test:
    commands:
        - test -f ${PREFIX}/lib/libzmq.a
        - test -f ${PREFIX}/lib/libzmq.so
        - test -f ${PREFIX}/lib/libzmq.so.5
        - test -f ${PREFIX}/lib/cmake/ZeroMQ/ZeroMQConfig.cmake
        - test -f ${PREFIX}/lib/cmake/ZeroMQ/ZeroMQConfigVersion.cmake
        - ${PREFIX}/bin/curve_keygen
about:
    home: http://zeromq.org
    license: LGPL 3
    summary: A high-performance asynchronous messaging library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - JohanMabille
        - SylvainCorlay
        - jakirkham
        - minrk
