# This file created by conda-build 3.19.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Mar 27 14:56:54 2020
# ------------------------------------------------

package:
    name: configurable-http-proxy
    version: 4.2.1
source:
    fn: configurable-http-proxy-4.2.1.tar.gz
    sha256: f40c055b881805636f874fea4a9e5af37ba375d04b2e67f11e32acc8addf3f6f
    url: https://registry.npmjs.org/configurable-http-proxy/-/configurable-http-proxy-4.2.1.tgz
build:
    number: '0'
    script:
        - npm pack
        - NPM_CONFIG_USERCONFIG=/tmp/nonexistentrc npm install -g configurable-http-proxy-4.2.1.tgz
    string: node10_h1f298a6_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2019.11.28 hecc5488_0
        - icu 64.2 he1b5a44_1
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - libuv 1.32.0 h516909a_0
        - nodejs 10.16.3 h10a4023_0
        - openssl 1.1.1e h516909a_0
        - zlib 1.2.11 h516909a_1006
    run:
        - nodejs 10.*
test:
    commands:
        - configurable-http-proxy -h
        - test -f $PREFIX/bin/configurable-http-proxy
about:
    home: https://github.com/jupyterhub/configurable-http-proxy
    license: BSD 3-Clause
    license_file: LICENSE
    summary: node-http-proxy plus a REST API
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
        - willingc
