# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Apr 17 17:26:17 2020
# ------------------------------------------------

package:
    name: brotlipy
    version: 0.7.0
source:
    fn: brotlipy-0.7.0.tar.gz
    sha256: 36def0b859beaf21910157b4c33eb3b06d8ce459c942102f16988cca6ea164df
    url: https://pypi.io/packages/source/b/brotlipy/brotlipy-0.7.0.tar.gz
build:
    number: '1000'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37h8f50634_1000
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - binutils_impl_linux-64 2.34 h53a641e_0
        - binutils_linux-64 2.34 hc952b39_18
        - gcc_impl_linux-64 7.3.0 hd420e75_5
        - gcc_linux-64 7.3.0 h553295d_18
        - ld_impl_linux-64 2.34 h53a641e_0
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2020.4.5.1 hecc5488_0
        - certifi 2020.4.5.1 py37hc8dfbb8_0
        - cffi 1.14.0 py37hd463f26_0
        - ld_impl_linux-64 2.34 h53a641e_0
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1f h516909a_0
        - pycparser 2.20 py_0
        - python 3.7.6 h8356626_5_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 hf8c457e_0
        - setuptools 46.1.3 py37hc8dfbb8_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - xz 5.2.5 h516909a_0
        - zlib 1.2.11 h516909a_1006
    run:
        - cffi >=1.0.0
        - libgcc-ng >=7.3.0
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
test:
    imports:
        - brotli
about:
    dev_url: https://github.com/python-hyper/brotlipy
    home: https://github.com/python-hyper/brotlipy
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Python bindings to the Brotli compression library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - astaric
        - primozgodec
