# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Aug  4 21:23:04 2019
# ------------------------------------------------

package:
    name: mako
    version: 1.1.0
source:
    fn: Mako-1.1.0.tar.gz
    sha256: a36919599a9b7dc5d86a7a8988f23a9a3a3d083070023bab23d64f7f1d1e0a4b
    url: https://pypi.org/packages/source/M/Mako/Mako-1.1.0.tar.gz
build:
    entry_points:
        - mako-render=mako.cmd:cmdline
    noarch: python
    number: '0'
    preserve_egg_dir: true
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.6.16 hecc5488_0
        - certifi 2019.6.16 py27_1
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - markupsafe 1.1.1 py27h14c3975_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - pip 19.2.1 py27_0
        - python 2.7.15 h5a48372_1009
        - readline 8.0 hf8c457e_0
        - setuptools 41.0.1 py27_0
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - wheel 0.33.4 py27_0
        - zlib 1.2.11 h516909a_1005
    run:
        - markupsafe >=0.9.2
        - python
test:
    commands:
        - mako-render --help
    imports:
        - mako
        - mako.ext
about:
    dev_url: https://bitbucket.org/zzzeek/mako/src
    doc_url: http://docs.makotemplates.org/en/latest/
    home: http://www.makotemplates.org/
    license: MIT
    license_file: LICENSE
    summary: A super-fast templating language that borrows the best ideas from the
        existing templating languages.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
