# This file created by conda-build 3.19.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Mar 12 17:26:35 2020
# ------------------------------------------------

package:
    name: entrypoints
    version: '0.3'
source:
    sha256: c70dd71abe5a8c85e55e12c19bd91ccfeec11a6e99044204511f9ed547d48451
    url: https://pypi.io/packages/source/e/entrypoints/entrypoints-0.3.tar.gz
build:
    number: '1001'
    script:
        - flit build --format wheel
        - /home/conda/feedstock_root/build_artifacts/entrypoints_1584034053506/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
            -m pip install dist/entrypoints-0.3-py2.py3-none-any.whl --no-deps --ignore-installed
            --no-cache-dir -vvv
    string: py37hc8dfbb8_1001
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2019.11.28 hecc5488_0
        - certifi 2019.11.28 py38h32f6830_1
        - cffi 1.14.0 py38hd463f26_0
        - chardet 3.0.4 py38_1003
        - cryptography 2.8 py38h72c5cf5_1
        - docutils 0.16 py38h32f6830_1
        - flit 2.2.0 py_0
        - flit-core 2.2.0 py_0
        - idna 2.9 py_1
        - ld_impl_linux-64 2.33.1 h53a641e_8
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d h516909a_0
        - pip 20.0.2 py_2
        - pycparser 2.20 py_0
        - pygments 2.6.1 py_0
        - pyopenssl 19.1.0 py_1
        - pysocks 1.7.1 py38_0
        - python 3.8.2 h9d8adfe_4_cpython
        - python_abi 3.8 1_cp38
        - pytoml 0.1.21 py_0
        - readline 8.0 hf8c457e_0
        - requests 2.23.0 py38_0
        - requests_download 0.1.2 py_1
        - setuptools 46.0.0 py38h32f6830_2
        - six 1.14.0 py_1
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - urllib3 1.25.7 py38_0
        - wheel 0.34.2 py_1
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2019.11.28 hecc5488_0
        - certifi 2019.11.28 py37hc8dfbb8_1
        - ld_impl_linux-64 2.33.1 h53a641e_8
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d h516909a_0
        - pip 20.0.2 py_2
        - python 3.7.6 h357f687_4_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 hf8c457e_0
        - setuptools 46.0.0 py37hc8dfbb8_2
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py_1
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
    run:
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
test:
    imports:
        - entrypoints
about:
    home: https://entrypoints.readthedocs.io/
    license: MIT
    license_file: LICENSE
    summary: Discover and load entry points from installed packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
        - ocefpaf
        - pelson
        - takluyver
