# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri May 24 00:55:05 2019
# ------------------------------------------------

package:
    name: python-json-logger
    version: 0.1.11
source:
    fn: python-json-logger-0.1.11.tar.gz
    sha256: b7a31162f2a01965a5efb94453ce69230ed208468b0bbc7fdfc56e6d8df2e281
    url: https://pypi.io/packages/source/p/python-json-logger/python-json-logger-0.1.11.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    build:
        - ca-certificates 2019.3.9 hecc5488_0
        - certifi 2019.3.9 py27_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - pip 19.1 py27_0
        - python 2.7.15 h721da81_1008
        - readline 7.0 hf8c457e_1001
        - setuptools 41.0.1 py27_0
        - sqlite 3.28.0 h8b20d00_0
        - tk 8.6.9 h84994c4_1001
        - wheel 0.33.4 py27_0
        - zlib 1.2.11 h14c3975_1004
    run:
        - python
test:
    imports:
        - pythonjsonlogger
about:
    description: 'This library is provided to allow standard python logging to output
        log

        data as json objects. With JSON we can make our logs more readable by

        machines and we can stop writing custom parsers for syslog type records.

        '
    home: http://github.com/madzak/python-json-logger
    license: BSD 2-clause
    license_family: BSD
    license_file: LICENSE
    summary: A python library adding a json log formatter
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - sodre
        - ukaratay
