# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Feb  2 23:56:52 2019
# ------------------------------------------------

package:
    name: python-editor
    version: 1.0.4
source:
    fn: python-editor-1.0.4.tar.gz
    sha256: 51fda6bcc5ddbbb7063b2af7509e43bd84bfc32a4ff71349ec7847713882327b
    url: https://pypi.org/packages/source/p/python-editor/python-editor-1.0.4.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/python-editor_1549151923271/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py_0
requirements:
    host:
        - ca-certificates 2018.11.29 ha4d7672_0
        - certifi 2018.11.29 py27_1000
        - libffi 3.2.1 hf484d3e_1005
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.0.2p h14c3975_1002
        - pip 19.0.1 py27_0
        - python 2.7.15 h938d71a_1006
        - readline 7.0 hf8c457e_1001
        - setuptools 40.7.1 py27_0
        - sqlite 3.26.0 h67949de_1000
        - tk 8.6.9 h84994c4_1000
        - wheel 0.32.3 py27_0
        - zlib 1.2.11 h14c3975_1004
    run:
        - python
test:
    imports:
        - editor
about:
    dev_url: https://github.com/fmoo/python-editor
    home: https://github.com/fmoo/python-editor
    license: Apache 2.0
    license_family: Apache
    license_file: LICENSE
    summary: Programmatically open an editor, capture the result.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
