# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon May 25 13:09:48 2020
# ------------------------------------------------

package:
    name: prometheus_client
    version: 0.8.0
source:
    sha256: ac8f06e260aaef5467be369032c7a02e17fd39e6d2ac933964757cb6c92da678
    url: https://github.com/prometheus/client_python/archive/v0.8.0.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/prometheus_client_1590412252446/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . -vv
    string: pyh9f0ad1d_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - binutils_impl_linux-64 2.34 h53a641e_2
        - ca-certificates 2020.4.5.1 hecc5488_0
        - certifi 2020.4.5.1 py36h9f0ad1d_0
        - gcc_impl_linux-64 7.5.0 hd420e75_6
        - gfortran_impl_linux-64 7.5.0 hdf63c60_6
        - gxx_impl_linux-64 7.5.0 hdf63c60_6
        - ld_impl_linux-64 2.34 h53a641e_2
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgfortran-ng 7.5.0 hdf63c60_6
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1g h516909a_0
        - pip 20.1.1 pyh9f0ad1d_0
        - python 3.6.10 h8356626_1011_cpython
        - python_abi 3.6 1_cp36m
        - readline 8.0 hf8c457e_0
        - setuptools 46.4.0 py36h9f0ad1d_0
        - sqlite 3.30.1 hcee41ef_0
        - sysroot_linux-64 2.12 h3a0023d_3
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py_1
        - xz 5.2.5 h516909a_0
        - zlib 1.2.11 h516909a_1006
    run:
        - python
test:
    commands:
        - pip check
    imports:
        - prometheus_client
        - prometheus_client.bridge
    requires:
        - pip
about:
    home: https://github.com/prometheus/client_python
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
    summary: Python client for the Prometheus monitoring system
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jessicaaustin
        - kwilcox
        - ocefpaf
