# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Apr 13 18:48:07 2020
# ------------------------------------------------

package:
    name: jinja2
    version: 2.11.2
source:
    fn: Jinja2-2.11.2.tar.gz
    sha256: 89aab215427ef59c34ad58735269eb58b1a5808103067f7bb9d5836c651b3bb0
    url: https://pypi.io/packages/source/J/Jinja2/Jinja2-2.11.2.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/jinja2_1586803736015/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps -vv
    string: pyh9f0ad1d_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2020.4.5.1 hecc5488_0
        - certifi 2020.4.5.1 py36h9f0ad1d_0
        - ld_impl_linux-64 2.34 h53a641e_0
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1f h516909a_0
        - pip 20.0.2 py_2
        - python 3.6.10 h8356626_1010_cpython
        - python_abi 3.6 1_cp36m
        - readline 8.0 hf8c457e_0
        - setuptools 46.1.3 py36h9f0ad1d_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py_1
        - xz 5.2.5 h516909a_0
        - zlib 1.2.11 h516909a_1006
    run:
        - markupsafe >=0.23
        - python
        - setuptools
test:
    imports:
        - jinja2
about:
    description: 'Jinja2 is a full featured template engine for Python. It has full
        unicode

        support, an optional integrated sandboxed execution environment, widely

        used and BSD licensed.

        '
    dev_url: https://github.com/pallets/jinja
    doc_source_url: https://github.com/pallets/jinja/blob/master/docs/index.rst
    doc_url: http://jinja.pocoo.org/docs/dev/
    home: http://jinja.pocoo.org
    license: 3-Clause BSD
    license_file: LICENSE.rst
    summary: An easy to use stand-alone template engine written in pure python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - nehaljwani
        - scopatz
